#!/usr/bin/env bash

str=$1
container_id=$(docker ps -qf "name=web")

# Bash do container
if [ "$str" = "bash" ]; then
    docker exec -it $container_id /bin/bash
fi

# Instala o Laravel
if [ "$str" = "laravel:install" ]; then
    docker exec -it $container_id /bin/bash -c "
    rm -rf *.*
    composer create-project laravel/laravel .
    ls -la
    "
fi

# Instala o Lumen
if [ "$str" = "lumen:install" ]; then
    docker exec -it $container_id /bin/bash -c "
    rm -rf *.*
    composer create-project --prefer-dist laravel/lumen .
    ls -la
    "
fi

# Permissões do container
if [ "$str" = "laravel:permissions" ]; then
    docker exec -it $container_id /bin/bash -c "
    chown -R 1000:1000 ./
    php artisan storage:link
    chmod o+w ./storage/ -R
    "
fi

# Permissões do container
if [ "$str" = "lumen:permissions" ]; then
    docker exec -it $container_id /bin/bash -c "
    chown -R 1000:1000 ./
    ls -la
    "
fi
