#!/usr/bin/env bash

str=$1
container_id=$(docker ps -qf "name=web")

# Bash do container
if [ "$str" = "bash" ]; then
    docker exec -it $container_id /bin/bash
fi

# Instala o Laravel
if [ "$str" = "laravel:install" ]; then
    docker exec -it $container_id /bin/bash -c "
    rm -rf *.*
    composer create-project laravel/laravel .
    ls -la
    "
fi

# Instala o Lumen
if [ "$str" = "lumen:install" ]; then
    docker exec -it $container_id /bin/bash -c "
    rm -rf *.*
    composer create-project --prefer-dist laravel/lumen .
    ls -la
    "
fi

# Permissões do container
if [ "$str" = "laravel:permissions" ]; then
    docker exec -it $container_id /bin/bash -c "
    addgroup -g 1000 www-data
    adduser -D -u 1000 -G www-data -s /sbin/nologin www-data
    chown -R 1000:www-data /var/www/html
    chown -R www-data:www-data /var/www/html/storage
    php artisan storage:link
    chmod o+w /var/www/html/storage/ -R
    "
fi

# Permissões do container
if [ "$str" = "lumen:permissions" ]; then
    docker exec -it $container_id /bin/bash -c "
    addgroup -g 1000 www-data
    adduser -D -u 1000 -G www-data -s /sbin/nologin www-data
    chown -R 1000:www-data /var/www/html
    chown -R www-data:www-data /var/www/html/storage
    chmod o+w /var/www/html/storage/ -R
    ls -la
    "
fi


# Permissões do container
if [ "$str" = "lumen:test" ]; then
    docker exec -it $container_id /bin/bash -c "
    ./vendor/bin/phpunit
    "
fi