version: '3.1'

services:

  # Web
  web:
    build:
      context: ./.docker/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel

  # Database
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'laravel'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'laravel'
        MYSQL_USER: 'laravel'
        MYSQL_PASSWORD: 'laravel'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - 'db_data:/var/lib/mysql'
    networks:
        - laravel

networks:
  laravel:

volumes:
  db_data: